#!/usr/bin/env python3
"""
优酷视频下载 - Cookie 登录助手

使用方法：
1. 先运行此脚本：python login_and_save_cookie.py
2. 在弹出的浏览器中登录优酷
3. 等待自动保存 Cookie
4. 然后就可以批量下载了
"""

from DrissionPage import ChromiumPage
import tempfile
import os
import time

from crawagent.config.settings import get_logger
logger = get_logger(__name__)


def fix_domain(domain):
    """修复 domain 格式，确保以点开头"""
    domain = domain.strip()
    if domain and not domain.startswith('.'):
        if domain.startswith('www.'):
            domain = '.' + domain[4:]
        else:
            domain = '.' + domain
    return domain


def main():
    logger.info("优酷 Cookie 获取助手")
    logger.info("1. 即将打开浏览器，请登录优酷账号")
    logger.info("2. 登录后等待页面完全加载")
    logger.info("3. 程序会自动检测登录状态并保存 Cookie")
    
    # 打开浏览器访问优酷
    page = ChromiumPage()
    page.get('https://youku.com')
    
    logger.info("请在浏览器中登录优酷...")
    logger.info("登录后等待 10 秒让 Cookie 生效...")
    time.sleep(10)
    
    # 获取 cookies
    cookies = page.cookies()
    logger.info(f"获取到 {len(cookies)} 个 cookies")
    
    # 过滤 youku 相关的 cookies
    youku_cookies = [c for c in cookies if 'youku' in c.get('domain', '').lower() 
                     or 'taobao' in c.get('domain', '').lower()
                     or 'alibaba' in c.get('domain', '').lower()]
    logger.info(f"优酷相关 cookies: {len(youku_cookies)}")
    
    if len(youku_cookies) == 0:
        logger.warning("没有找到优酷相关的 cookies，可能登录失败")
    else:
        # 保存到文件
        cookie_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'youku_cookies.txt')
        with open(cookie_file, 'w', encoding='utf-8') as f:
            f.write('# Netscape HTTP Cookie File\n')
            f.write('# This file was generated by CrawAgent\n')
            for cookie in youku_cookies:
                domain = cookie.get('domain', '')
                # 修复 domain 格式
                domain = fix_domain(domain)
                name = cookie.get('name', '')
                value = cookie.get('value', '')
                path = cookie.get('path', '/')
                secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
                expiry = int(cookie.get('expiry', 9999999999))
                # 添加 httponly 标记（如果需要）
                f.write(f'{domain}\tTRUE\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n')
        
        logger.info(f"Cookie 已保存到: {cookie_file}")
        logger.info("下一步：")
        logger.info(f"  1. Cookie 文件: {cookie_file}")
        logger.info("  2. 在下载脚本中使用 cookies_file 参数")
    
    page.quit()


if __name__ == '__main__':
    main()
